version: '3.7'

services:
  db:
    container_name: some-pg
    image: postgres:9
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    command: postgres

volumes:
  db: {}
